endpoints:
    health:
        time-to-live: 1000
    shutdown:
        enabled: true
info:
    artifact: ff4j-sample-springboot
    group: org.ff4j.samples
    name: Sample FF4J SpringBoot
    version: 1.3.5-SNAPSHOT
management:
    address: 127.0.0.1
    context-path: /management
    security:
        enabled: false

spring:
    application:
        name: demoff4j
    endpoints:
        health:
            time-to-live: 1000
        shutdown:
            enabled: true
    info:
        artifact: ff4j-sample-springboot
        group: org.ff4j.samples
        name: Sample FF4J SpringBoot
        version: 1.3.5-SNAPSHOT
    management:
        address: 127.0.0.1
        context-path: /management
        security:
            enabled: false

eureka:
  client:
    service-url:
      defautlZone: http://admin:admin@localhost:8761/eureka/

# Common configuration shared between all applications

ff4j:
    features:
        testflag:
            enable: false
            flipStrategy:
                clazz: org.ff4j.strategy.time.OfficeHourStrategy
                params:
                    monday: 08:00-12:00,13:30-18:00
                    tuesday: 08:00-12:00,13:30-18:00
    properties:
        testprop:
            type: string
            value: test
            description: some string
            fixedValues:
                - test
                - test2
#    webapi:
#        authentication: false
#        authorization: false